### ISSUE TITLE
[Doplnění] Přepínadlo jazyků

### ISSUE THREAD

**Issue by Fili00** [marekCs/ferox.princeston.eu#1]
Dokončit překlad cz a aj a následně udělat přepínadlo mezi jazyky

**Comment by marekCs** [comment]
hotovo

**Comment by Fili00** [comment]
Po kliknutí na českou verzi se jen načte znova anglická. Asi nemá odkaz?
Po kliknutí na kontakty se mi z anglické přepne na cz
Na anglické homepage zůstala česká věta: Inovativní technologie na úsporu paliva

**Comment by marekCs** [comment]
mě vše funguje dobře, ale dělal jsem tam do poslední chvíle nějaké úpravy, takže zkuste nyní. Pokud by tam byla ještě chyba, prosím o doplnění.

**Comment by Fili00** [comment]
Koukám, že na jiném prohlížeči mi to funguje, takže to bude chyba nejspíš u mě.

**Comment by Fili00** [comment]
Zde vás ještě poprosím po předchozí domluvě s otcem, udělat překlad pro maďary, Poláky a design přepínání udělat tímto stylem? 
![obrazek](https://github.com/marekCs/ferox.princeston.eu/assets/152264481/c5ec62bd-bc13-463f-a9af-a83af8e6f152)

**Comment by marekCs** [comment]
Ok uvidím co se dá dělat. Systémové části Drupalu jsou pevně nastavené, i jejich chování a vzhled, jazyk tam patří mezi to, a přepínač jazyka je v Selectu napevno. Zkusím ale naprogramovat nějaký hook.

Pěkný den!
Marek Dvořák

Odesláno z bezpečného [Proton Mailu](https://proton.me/).

čtvrtek, 30. listopadu 2023 v 16:44, Fili00 ***@***.***> napsal/a:

**Comment by marekCs** [comment]
hotovo to zobrazení vlajek, překlady ostatních jazyků až nakonec.
