### ISSUE TITLE
[Doplnění] úprava koleček

### ISSUE THREAD

**Issue by Fili00** [marekCs/ferox.princeston.eu#4]
Upravit kolečka podle designu. Text dát vedle koleček. Kolečku dát barvu pozadí. zvětšit a ztlustšit čísla a procenta
![obrazek](https://github.com/marekCs/ferox.princeston.eu/assets/152264481/c0bc7e45-cf61-4245-9a07-95ada7b560ab)

**Comment by marekCs** [comment]
![Screenshot 2023-11-30 141842](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/eeff4e6e-93cb-426f-a8c6-7233fa44566b)
tohle je asi nejvíc co aktuálně dokážu, nedaří se mi tam vecpat to tmavší pozadí do toho kruhu. něco to přepisuje a nevím co, jinak vše sedí.

**Comment by Fili00** [comment]
Jo, nechme to, vypadá to dobře. Jen nevím jestli je to zas jen u mě, ale když jdu přes firefox, tak mi to udělá toto
![obrazek](https://github.com/marekCs/ferox.princeston.eu/assets/152264481/447a4e06-e747-4b99-8d63-06844a55e41f)

**Comment by marekCs** [comment]
Zkuste českou verzi já zapomněl upravit zdrojaky pro anglickou verzi. Taky mám Firefox ale Developer edition.

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

V čt, lis 30, 2023 v 16:22, Fili00 ***@***.***(mailto:V čt, lis 30, 2023 v 16:22, Fili00 <<a href=)> napsal/a:

**Comment by Fili00** [comment]
Česká mi funguje

**Comment by marekCs** [comment]
hotovo
