### ISSUE TITLE
[Nový požadavek] Nová stránka "Výsledky testů"

### ISSUE THREAD

**Issue by Fili00** [marekCs/ferox.princeston.eu#5]
Nějaký carousel, který bude na celou stránku, kde bude rovnou vidět 2 až 3 fotky. Budou to fotky, kde jsou záznamy toho, když se dělali testy. Pak přidat záložku "Testy" do hlavičky. Jak cz tak en

**Comment by marekCs** [comment]
poprosím nějaký grafický náčrt jak by to mělo vypadat

**Comment by Fili00** [comment]
Zkusme tedy nějak takto: 
![obrazek](https://github.com/marekCs/ferox.princeston.eu/assets/152264481/5633f640-7f5d-4c12-8fb1-63073b5f5e44)
S tím, že tam bude takto jeden velký obrázek, který bude po kliknutí na tlačítko rotovat. Šlo by aby se po kliknutí zvětšil?
Fotky pošlu večer

**Comment by Fili00** [comment]
https://drive.google.com/drive/u/0/folders/10_88JDp_Krvov77jW7pmpbyLSR5THyFc
Stránku jménem č. 17 dát pro česko na první místo a pro ostatní země vypnout.

**Comment by marekCs** [comment]
ok pokud tomu dobře rozumím, pro čj. variantu bude první dvojfotka česká zbytek ty ostatní testy, pro ostatní jazyky budou jen ty ostatní jazyky, česká tam nebude.  První bude třeba angličtina.

**Comment by Fili00** [comment]
Přesně tak, jen u té cz stránky budou na prvním místě ty české

**Comment by marekCs** [comment]
hotovo
