### ISSUE TITLE
[Doplnění] - komentáře

### ISSUE THREAD

**Issue by marekCs** [marekCs/ferox.princeston.eu#6]
Prosím o návrh struktury komentářů, které budou jako Carousel, stále to sedí jako to bylo na této fotce ![Web 1920 – 1](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/b818370d-52c9-4d55-ad7c-25b5fe032d9a) ? Jestli dobře vidím tak je tam komentář, jméno a pozice. Asi budu potřebovat i nadpis, ale to mohu skrýt.

Pokud to sedí, prosím o zaslání textů a jmen a pozic komentujících.

**Comment by Fili00** [comment]
Tady jsme to zatím vzali odtud: https://feroxfueltabs.com/
Dole na stránce jsou takto jednoduše tři komentáře. Až budou přibývat nějaké naše, tak budeme přidávat, ale toto je zatím vše co máme

**Comment by marekCs** [comment]
prosím doplnit přesně texty které tam mají být, nebo mám zkopírovat ty tři z https://feroxfueltabs.com/?

**Comment by marekCs** [comment]
prosím o kontrolu komentářů: [https://ferox.princeston.eu/test](https://ferox.princeston.eu/test)
plus posílám typy hvězdiček které tam jde napasovat
![Screenshot 2023-12-05 145342](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/c99cf97b-3cd5-45f2-9f7d-04dcc096902d)
![Screenshot 2023-12-05 145636](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/41626b67-40dd-43f2-9a32-a6e5c42b315a)
![Screenshot 2023-12-05 145833](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/c655054f-b0ae-429d-a77e-720020aeb80c)

**Comment by Fili00** [comment]
Texty zkopírujte z toho webu. Jinak komentáře vypadají dobře.
Šli by ty poslední hvězdičky přebarvit na bílou. Ty první dvě mi připadají moc oldschool

**Comment by marekCs** [comment]
Bohužel nejdou přebarvit, je to obrázek. Leda byste mi nějaký obrázek vyrobil a nahradíme to.

Pěkný den!
Marek Dvořák

Odesláno z bezpečného [Proton Mailu](https://proton.me/).

středa, 6. prosince 2023 v 10:11, Fili00 ***@***.***> napsal/a:

**Comment by marekCs** [comment]
hotovo, obrázek hvězdiček stačí dodat kdykoli do emailu a vyměním to, rozměr 16 x 42. Obrázky vypadají takto: https://ferox.princeston.eu/modules/contrib/fivestar/widgets/outline/star.png
nahoře je barva pro off (když je hlasování vypnuté), uprostřed pro on a spodní pro hover efekt.
