### ISSUE TITLE
[Doplnění] Dokumenty

### ISSUE THREAD

**Issue by Fili00** [marekCs/ferox.princeston.eu#8]
Ještě jednou posílám ty dokumenty, ať to máme na jednom místě
https://drive.google.com/drive/u/0/folders/1UX1eAMi5S8EOFi5XEmz7OaZUQMfpARZK
A nevím jestli tam jsou všechny, které potřebujemem tak radši posílám originální. Ty pak stejně budou potřeba pro anglickou verzi: https://feroxfueltabs.com/documentation/

**Comment by marekCs** [comment]
ok takže je tam naskládám nějak podobně jako to mají na https://feroxfueltabs.com/documentation/

**Comment by Fili00** [comment]
Ano a nevím jestli jsem to už někde nepsal, ale odkaz dáme pouze do patičky

**Comment by marekCs** [comment]
Ok rozumím. Dnes už pokračovat nebudu, zítra na to ale zase přes den skočím.

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

V čt, lis 30, 2023 v 14:41, Fili00 ***@***.***(mailto:V čt, lis 30, 2023 v 14:41, Fili00 <<a href=)> napsal/a:

**Comment by marekCs** [comment]
Prosím napárovat české verze k anglickým, nebo to nemá být 1:1?
![Screenshot 2023-12-02 165700](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/6140bab6-4c3f-430e-930c-a711be76bade)
![Screenshot 2023-12-02 165830](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/c005e996-6d1a-47cf-a5f5-e56038fd5fc6)
@Fili00

**Comment by marekCs** [comment]
Už to chápu, nemusí to být 1:1. Jen dodatek, anglický soubor Saving graph není v angličtině ale ve španělštině. [https://feroxfueltabs.com/wp-content/uploads/Grafica-de-Ahorro-Vehiculos.pdf](https://feroxfueltabs.com/wp-content/uploads/Grafica-de-Ahorro-Vehiculos.pdf)

**Comment by marekCs** [comment]
Stačí takto jednoduše? Je to na localhostu ne na ostré verzi ještě
![Screenshot 2023-12-02 233209](https://github.com/marekCs/ferox.princeston.eu/assets/55324027/f1ff4b69-9084-4e7e-800b-aca2a773918c)

**Comment by Fili00** [comment]
Já üpřímně nevím, co všechno je potřeba tam mít, ale udělal bych to tak, že bych tam dal vše a na cz stránku také vše, jen to co už je přeložené, tak pouze cz verzi.

Ano, takto jednoduše to stačí

**Comment by marekCs** [comment]
hotovo
