### ISSUE TITLE
[Doplnění] Carousel

### ISSUE THREAD

**Issue by Fili00** [marekCs/ferox.princeston.eu#9]
Šlo by zde přidat počet oprázků v carouselu? 

![obrazek](https://github.com/marekCs/ferox.princeston.eu/assets/152264481/82360efb-db0c-4260-88f6-8d617c0886b1)

**Comment by marekCs** [comment]
Mrknu na to.

Pěkný den!
Marek Dvořák

Odesláno z bezpečného [Proton Mailu](https://proton.me/).

čtvrtek, 30. listopadu 2023 v 16:47, Fili00 ***@***.***> napsal/a:

**Comment by marekCs** [comment]
hotovo
